Make --help/--version work w/ !allowUnknownFlags
sindresorhus/meow pull request #198
Opened 2021-09-15 20:10 UTC by msabramo

Make `--help` and `--version` work with `allowUnknownFlags: false`

Fixes: GH-197

Issue originally discovered with `chalk-cli` in https://github.com/chalk/chalk-cli/issues/32

2021-09-15 20:14 UTC, sindresorhus commented
Can you add tests? 🙏

2021-09-15 20:17 UTC, msabramo commented
Yeah I thought of that right after I submitted this. 😄

2021-09-15 21:02 UTC, msabramo commented
See 368e760 for tests.

Unfortunately, I think my change broke 20 other unrelated existing tests, so I may have to think of a better way to accomplish the fix without affecting other stuff.

2021-09-16 01:37 UTC, msabramo commented
OK, I got all the tests passing, but honestly I feel like I was hacking around without really understanding what the behavior should  be. So someone should take a close look and make sure I didn't mess things up.

2021-09-26 10:23 UTC, sindresorhus requested changes

2021-09-26 10:23 UTC, sindresorhus commented on index.js
> +		options.flags.help = {type: 'boolean'};
You are modifying the user's input object here. You should not do that.

2021-09-26 10:23 UTC, sindresorhus commented on index.js
> +	let addedAutoHelp = false;
```suggestion
	let didAddAutoHelp = false;
```

2021-09-26 10:25 UTC, sindresorhus commented
> So someone should take a close look and make sure I didn't mess things up.

That someone is me and I don't think I'll time to review this in detail for quite some time, unfortunately.

2021-11-16 14:54 UTC, LitoMore requested changes

2021-11-16 14:54 UTC, LitoMore commented on test/fixtures/fixture-allow-unknown-flags.js
> +
```suggestion
```

2022-01-25 09:51 UTC, sindresorhus commented
Closing for lack of activity.

2022-01-25 09:51 UTC, closed without merging