Add `commands` option
sindresorhus/meow pull request #205
Opened 2022-03-04 15:47 UTC by skoshx

This commit adds support for subcommands.

Fixes #69

2022-03-07 06:58 UTC, sindresorhus requested changes

2022-03-07 06:58 UTC, sindresorhus commented on index.d.ts
> +  Define subcommands.
Use tab-indentation.

2022-03-07 06:58 UTC, sindresorhus commented on index.d.ts
> +    unicorn: (helpText, options) => meow({
The `helpText` argument is moot. `helpText` can already be passed in `options`.

2022-03-07 06:58 UTC, sindresorhus commented on index.d.ts
> +  Define subcommands.
The description needs to be more extensive. It should describe how it works (that it doesn't actually call any commands for you, etc).

2022-03-07 06:58 UTC, sindresorhus commented on index.d.ts
> +  commands: {
The example should be complete and runnable. I think it's better to define the subcommand function at the top-level, for readability.

2022-03-07 06:58 UTC, sindresorhus commented on index.js
> +		commands[command] = meowInstance(helpText, {...options, argv: process.argv.slice(3), commands: {}});
Pass `helpText` in `options`.

2022-03-07 06:58 UTC, sindresorhus commented on test/fixtures/fixture-commands.js
> +  `,
Tab-indentation.

2022-03-07 06:58 UTC, sindresorhus commented on test/fixtures/fixture-commands.js
> +const subcommand = (helpText, options = {}) => meow({
```suggestion
const subcommand = (helpText, options) => meow({
```

The `options` should be guaranteed. Make sure the code guarantees it to exist.

2022-03-07 06:58 UTC, sindresorhus commented on index.d.ts
> +  commands: {
The example should also illustrate how one might check for and call code for the subcommand.

2022-03-07 06:58 UTC, sindresorhus commented on index.d.ts
> +  */
This also needs to be documented in the readme.

2022-06-03 09:16 UTC, backtolife2021 commented
@skoshx  This is a very useful feature, this thread seems to have stalled for a long time, is there any progress now?

2022-06-03 14:30 UTC, skoshx commented
@backtolife2021 I made the changes requested by Sindre, other than that everything is good to go, just waiting for Sindre's review.

friendly bump :) @sindresorhus

2022-07-24 18:36 UTC, skoshx commented
Closing in favor of PR #211

2022-07-24 18:36 UTC, closed without merging