Provide JSDoc comments for flag properties
sindresorhus/meow pull request #230
Opened 2023-03-24 17:11 UTC by tommy-mitchell

Adds JSDoc comments to each property of the type `Flag` so that Intellisense is provided when creating a flag:

<img width="878" alt="image" src="https://user-images.githubusercontent.com/1403701/227594339-ea2eb454-e436-4b5e-b29b-cbb3ba606657.png">

2023-03-24 17:24 UTC, sindresorhus requested changes

2023-03-24 17:24 UTC, sindresorhus commented on index.d.ts
> +		aliases: ['unicorns', 'u']
It should not contain `u` as users should use the shortFlag option for that.

2023-03-24 18:01 UTC, tommy-mitchell commented
I also added missing info to the flags JSDoc that was in the readme, and reordered the options to group similar concepts.

2023-03-24 18:04 UTC, tommy-mitchell commented
I'd like to help get #211 merged before the next release goes out. Should I open a new PR branched from it, or should it be reopened and I make PRs to its feature branch?

2023-03-24 18:29 UTC, sindresorhus commented
> Should I open a new PR branched from it,

New PR.

2023-03-24 18:29 UTC, merged

2023-03-25 00:53 UTC, tommy-mitchell commented
@sindresorhus unless you'd want to get #229 or #221 merged before the next release, you're good to put it out. Adding subcommands will probably be better with some general refactoring (separating utilities/steps into separate files, doing the same with tests/some fixtures, etc). I think that would be a good time to work on things like bundling and making errors consistent as well. I'll open a draft PR for that soon.

2023-03-25 01:58 UTC, sindresorhus commented
There's no rush in getting out a new version. It's going to be a major bump.