Separate `index.js` into different source files
sindresorhus/meow pull request #234
Opened 2023-03-28 20:26 UTC by tommy-mitchell

Per #233.

Tasks:

- [X] Target Node 14
- [X] Update dependencies, fix breaking changes
- [X] Separate into different source files
- [ ] Separate tests, consolidate via macros
- [ ] Add doc comments

Miscellaneous fixes:

- Fixed extraneous indents in fixtures
- Fixed test dealing with `process.title`, added note to readme/`index.d.ts` about overriding `options.pkg` (needs better wording)

2023-03-29 12:32 UTC, sindresorhus requested changes

2023-03-29 12:32 UTC, sindresorhus commented on readme.md
> +Note: setting this stops `meow` from finding a package.json.
```suggestion
Note: Setting this stops `meow` from finding a package.json.
```

2023-03-29 12:32 UTC, sindresorhus commented
This looks good so far 👍

2023-03-29 12:32 UTC, sindresorhus commented
You can target Node.js 16.

2023-03-29 17:27 UTC, tommy-mitchell commented
> You can target Node.js 16.

I'll do this in a separate PR then, the diff for this one is already pretty large and I'd like the changes from the improvements to be easier to see.

2023-03-29 17:35 UTC, tommy-mitchell commented on source/index.js
> +	process.title = result.pkg.bin ? Object.keys(result.pkg.bin)[0] : result.pkg.name;
Related to

> added note to readme/`index.d.ts` about overriding `options.pkg`

this check doesn't take into account that, if `options.pkg` was overridden, `pkg.name` might not exist

2023-03-29 17:59 UTC, sindresorhus commented
> By the way, is this list posted anywhere else? It's a nice checklist for a project bumping their Node version.

It's just my personal list. I think the Node.js team may post something similar on new major versions.

2023-03-29 17:59 UTC, sindresorhus commented
> I'll do this in a separate PR then, the diff for this one is already pretty large and I'd like the changes from the improvements to be easier to see.

👍

2023-03-29 18:59 UTC, tommy-mitchell commented
I've split up associated tests from `test.js` into their own files and consolidated via macros or utils where possible, especially for handling fixtures. Some more could be done here, but I think it's good enough for now.

2023-03-30 02:10 UTC, sindresorhus commented
Can you fix the merge conflict?

2023-03-30 05:38 UTC, tommy-mitchell commented
Should be good now

2023-03-30 07:33 UTC, merged