feat: support indent level as option
sindresorhus/meow pull request #241
Opened 2023-06-09 13:19 UTC by dylanarmstrong

Adds feature proposal from #240 to support `indent` as an option.

2023-08-01 06:37 UTC, dylanarmstrong commented
> The `index.test-d.ts` file needs to be updated.

Thanks, but per the attached issue, I’m unsure the project is going to actually use this PR. If I get approval there that this is wanted from maintainers, I’ll update this PR.

2024-02-04 07:04 UTC, dylanarmstrong commented
Hi, is there any update on this?

2024-02-04 16:16 UTC, sindresorhus requested changes

2024-02-04 16:16 UTC, sindresorhus commented on readme.md
> +Indentation to use on helpText.
Needs a better description.

2024-02-04 16:16 UTC, sindresorhus commented on source/index.d.ts
> +	@default true
Incorrect default.

2024-02-05 05:42 UTC, dylanarmstrong commented on source/index.d.ts
> +	@default true
Updated

2024-02-05 05:42 UTC, dylanarmstrong commented on readme.md
> +Indentation to use on helpText.
Updated

2024-02-05 05:43 UTC, dylanarmstrong commented
Thanks for the review @sindresorhus, I've updated the PR.

2024-02-06 09:53 UTC, merged