Bundle types in `index.d.ts`
sindresorhus/meow pull request #245
Opened 2023-08-27 15:36 UTC by tommy-mitchell

Fixes #244.

Uses [`rollup-plugin-dts`](https://github.com/Swatinem/rollup-plugin-dts) to bundle types and adds another `tsd` test for the bundled types.

2023-08-27 15:40 UTC, tommy-mitchell commented
I pinned the version of `type-fest`. In v4.3.0, the build fails due to https://github.com/sindresorhus/type-fest/issues/674.

2023-08-27 20:46 UTC, sindresorhus commented
https://github.com/sindresorhus/type-fest/releases/tag/v4.3.1

2023-08-27 20:48 UTC, sindresorhus requested changes

2023-08-27 20:48 UTC, sindresorhus commented on package.json
> +		"test": "xo && npm run build && ava && tsd -t build/index.d.ts"
```suggestion
		"test": "xo && npm run build && ava && tsd --typings build/index.d.ts"
```

2023-08-27 22:38 UTC, tommy-mitchell commented
Resolved.

2023-08-27 23:06 UTC, merged

2023-08-30 09:30 UTC, jaywcjlove commented
<img width="605" alt="image" src="https://github.com/sindresorhus/meow/assets/1680273/419edc6a-dbc6-4ab6-8557-e270eece6618">

Could not read type file anymore. @tommy-mitchell @sindresorhus 

```js
"typescript": "^5.2.2"
```

2023-08-30 23:53 UTC, tommy-mitchell commented
@sindresorhus do we need a `types` field in `package.json`? Not really sure why NPM isn't resolving it.

2023-08-31 00:31 UTC, jaywcjlove commented
> @sindresorhus do we need a `types` field in `package.json`? Not really sure why NPM isn't resolving it.

used in a project, the type could not be loaded @tommy-mitchell

2023-08-31 09:48 UTC, jaywcjlove commented
@sindresorhus thx!